services:
  api:
    build:
      context: .
    image: moleculer-ollama
    env_file: docker-compose.env
    environment:
      PORT: 80
      OLLAMA_HOST: http://localhost:11434
    network_mode: host
    restart: always
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: mariadb
      MARIADB_DATABASE: chat-ai
      MARIADB_ROOT_PASSWORD: mariadb
