services:

  services:
    build:
      context: .
    image: moleculer-ollama
    env_file: docker-compose.env
    environment:
      PORT: 3000
      OLLAMA_HOST: http://localhost:11434
    ports:
      - "3000:3000"
    networks:
      - host
